### ISSUE TITLE
Composer install error (fresh install)

### ISSUE THREAD

**Issue by kkorte** [hideyo/ecommerce#1]
<img width="631" alt="schermafbeelding 2017-12-20 om 22 57 52" src="https://user-images.githubusercontent.com/2678326/34230729-6393b082-e5d9-11e7-8371-f18ee84cd4bc.png">

**Comment by kkorte** [comment]
Fix:
`mkdir -p storage/framework/{sessions,views,cache} `

@matthijs-neijenhuijs Please update gitignore to include these subdirs

**Comment by matthijs-neijenhuijs** [comment]
@kkorte solved.
